### ISSUE TITLE
After successful install I don't see icons

### ISSUE THREAD

**Issue by echemik** [so2platform/LaraFly#1]
On console i see 

Request URL:http://larafly.dev/fonts/OpenSans-Regular-webfont.woff2
Request Method:GET
Status Code:404 Not Found
Remote Address:127.0.0.1:80
Response Headers
view source
Cache-Control:no-cache, private
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html; charset=UTF-8
Date:Sat, 25 Feb 2017 12:37:20 GMT
Server:nginx/1.10.2
Transfer-Encoding:chunked
Vary:Accept-Encoding
X-Powered-By:PHP/7.1.0
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Cookie:XSRF-TOKEN=eyJpdiI6Im01bmNha3BUVGdUeFJOcE9lOTdXYUE9PSIsInZhbHVlIjoiNm5TSEc0MWhMZTRzb1wvVm91czNxOHc4bUdxVTJQcWFXc2JjRG1JOTV5ZlhXUGROVzBEYndWXC81QXYyZ0ZqQVwvck4zXC9LZjBzRkxsczY4MEpZSFYxaFl3PT0iLCJtYWMiOiI3Y2Y1NzAzZWRhYzJiMTY0MzlkMTVmZjU0MWFkNjNiYjkzMmEzMWUzMDQ0NGQzYzdhMGE3NzMyOTljZTcyNGY0In0%3D; laravel_session=eyJpdiI6IjhkRXV0NE41anVkenM0eTZnODF4eGc9PSIsInZhbHVlIjoiOEhjVDN5K2c3QzM0RVVDVVg0aDFBQjZWamhtK1B5NlByRHhBUWIxMDRMMGMySFBsSWdjZFdZT005RGhKXC9MRlBHbk8xYUttRHVrQzZKbGxCRG0xRU9RPT0iLCJtYWMiOiI1Yjc4MDQxM2I5NTkwMjYxMTkxOGE2MThmYmQ3YWM4MzA4MDBjZThmYzVlZjY1MzdjMzBiZGNhMTY0ZmMxNTE1In0%3D
Host:larafly.dev
Origin:http://larafly.dev
Referer:http://larafly.dev/css/patternfly.min.css
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by alberto1el** [comment]
Oh yes I totally forgot, I did shipped the css and js files but I had gitignored the fonts folder.

I will include them and upload them in a moment.

To fix in your current installation you can npm run production (if you already did npm install to pull the npm packages) or you can wait for me to upload the files and just download the public folder and replace on your project.
