### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by aznain** [so2platform/LaraFly#3]
While using  an example from [PatternFly: Row Variation #5](http://www.patternfly.org/pattern-library/content-views/list-view/#/code ), I am getting an error 

> Uncaught ReferenceError: $ is not defined

Do i need to include jQuery or is it already added in 'patternfly.js' (only loaded js file) ?

**Comment by alberto1el** [comment]
Greetings and sorry for the late response.

I have uploaded an example view for that particular pattern:

https://github.com/so2platform/LaraFly/blob/master/resources/views/patternfly/list-view/row-variation-5.blade.php

If you check that example view you will see that all the javascript is in a script section, which in the layout file is called after the required scripts, which will fix your issue

If you update your copy of the project you can go to http://yourdomain/list-view/row-variation-5 and will be able to see it.

**Comment by aznain** [comment]
Thanks a lot for kind help and response. Much appreciated. Apologies for late reply as I missed the response. After following the example, It works now. 

After reading example, I change `<script>` to include javascript files instead of `@section('scripts')`.
